### ISSUE TITLE
Question from forum: Symbol footprints seem a bit large

### ISSUE THREAD

**Issue by poeschlr** [KiCad/Symbols.pretty#8]
Some of the symbols here seem to be a bit large. (Polarity marker and kicad logo.)

Link to forum question:
https://forum.kicad.info/t/ridiculously-big-silkscreen-symbols/7759

**Comment by SchrodingersGat** [comment]
Jan you scripted these ones right?

**Comment by jkriege2** [comment]
sorry ... I only did the Logos in the schematic lib,  not the ones here ...

**Comment by SchrodingersGat** [comment]
Ah looking at the logs it appears that these were made by @pointhi

**Comment by pointhi** [comment]
I generated all logos with specific heights to be consistent. It's hard to choose a sensible minimum size. I will generate smaller ones in the future, but I don't know at which height the Symbol is no longer readable

**Comment by pointhi** [comment]
Adding a Symbol Attribute which allows resizing of a footprint would be the sanest solution I think

**Comment by SchrodingersGat** [comment]
Sanest: Yes!
Simplest? Perhaps not.

I was also thinking that allowing resizing would be really handy.

**Comment by SchrodingersGat** [comment]
Closing this for now - if someone makes some smaller ones, they should be contributed to the new repo at https://github.com/kicad/kicad-footprints
